# Generated by Django 3.0.7 on 2020-06-07 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sauce', '0001_initial'),
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=0, max_digits=5)),
                ('ingredients', models.ManyToManyField(to='ingredient.Ingredient')),
                ('sauce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sauce.Sauce')),
            ],
        ),
    ]
