# Generated by Django 3.0.7 on 2020-06-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('due', models.DateTimeField()),
                ('pizzas', models.ManyToManyField(to='pizza.Pizza')),
            ],
        ),
    ]
