# Generated by Django 3.0.7 on 2020-06-11 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20200609_1730'),
        ('order', '0004_auto_20200609_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Pizza'),
        ),
    ]
