# Generated by Django 3.0.7 on 2020-06-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200611_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='pizza',
        ),
    ]
