# Generated by Django 3.0.7 on 2020-06-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_item', '0001_initial'),
        ('order', '0006_remove_orderitem_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(to='order_item.OrderItem'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
